title: What to Keep from Other Indians
author: Your Name
description: >- # this means to ignore newlines until "baseurl:"
  How and Why Strategic Privacy Unlocks Your True Potential.

baseurl: "/whattokeepfromindians" # repository name for GitHub Pages project site
url: "" # optional: set to https://<username>.github.io if desired

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Make posts always publish and use clean URLs
future: true
timezone: Asia/Kolkata
permalink: /chapters/:title/
