title: What to Keep from Other Indians
author: Your Name
description: >- # this means to ignore newlines until "baseurl:"
  How and Why Strategic Privacy Unlocks Your True Potential.

baseurl: ""
url: "https://whattokeepfromohterindians.nodesman-raj.workers.dev"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Make posts always publish and use clean URLs
future: true
timezone: Asia/Kolkata
permalink: /chapters/:title/
include:
  - sw.js
